/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.moviebooking;

import java.util.InputMismatchException;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author ADMIN
 */
public class BookingHomeFrame extends javax.swing.JFrame {

    
    /**
     * Creates new form BookingHomeFrame
     */
    public BookingHomeFrame() {
        initComponents();
        MovieController movie = new MovieController();
        DefaultTableModel table1 = (DefaultTableModel) CGVjTable.getModel();
        for(int i =0;i<movie.cgv.size();i++){
            table1.addRow(new Object[]{movie.cgv.get(i).getName(),movie.cgv.get(i).getGenre(),movie.cgv.get(i).getDirector(),movie.cgv.get(i).getReleaseYear(),movie.cgv.get(i).getMovieTime()});
        }
        DefaultTableModel table2 = (DefaultTableModel) GalaxyjTable.getModel();
        for(int i =0;i<movie.galaxy.size();i++){
            table2.addRow(new Object[]{movie.galaxy.get(i).getName(),movie.galaxy.get(i).getGenre(),movie.galaxy.get(i).getDirector(),movie.galaxy.get(i).getReleaseYear(),movie.galaxy.get(i).getMovieTime()});
        }
        DefaultTableModel table3 = (DefaultTableModel) LotteTable.getModel();
        for(int i =0;i<movie.lotte.size();i++){
            table3.addRow(new Object[]{movie.lotte.get(i).getName(),movie.lotte.get(i).getGenre(),movie.lotte.get(i).getDirector(),movie.lotte.get(i).getReleaseYear(),movie.lotte.get(i).getMovieTime()});
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DisplayPanel = new javax.swing.JPanel();
        CGVmovie = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        CGVjTable = new javax.swing.JTable();
        Search = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        BookingCGVMovie = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        MovieTime = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        Moviename = new javax.swing.JTextField();
        TicketPrice = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        SeatNumber = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        Director = new javax.swing.JTextField();
        Genre = new javax.swing.JTextField();
        Year = new javax.swing.JTextField();
        Hall = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        Purchase = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        Tprice = new javax.swing.JTextField();
        NSeat = new javax.swing.JComboBox<>();
        Galaxymovie = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        GalaxyjTable = new javax.swing.JTable();
        Search1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        BookingGalaxyMovie = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        Tprice1 = new javax.swing.JTextField();
        Moviename1 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        TicketPrice1 = new javax.swing.JTextField();
        Director1 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        Genre1 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        Year1 = new javax.swing.JTextField();
        SeatNumber1 = new javax.swing.JTextField();
        Hall1 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        MovieTime1 = new javax.swing.JSpinner();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        Nseat1 = new javax.swing.JComboBox<>();
        Lottemovie = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        LotteTable = new javax.swing.JTable();
        Search2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        BookingLooteMovie = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        Tprice2 = new javax.swing.JTextField();
        Moviename2 = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        TicketPrice2 = new javax.swing.JTextField();
        Director2 = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        Genre2 = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        Year2 = new javax.swing.JTextField();
        SeatNumber2 = new javax.swing.JTextField();
        Hall2 = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        MovieTime2 = new javax.swing.JSpinner();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        Nseat2 = new javax.swing.JComboBox<>();
        CinemaButton = new javax.swing.JPanel();
        Cgv = new javax.swing.JButton();
        Galaxy = new javax.swing.JButton();
        Lotte = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Booking movie");

        DisplayPanel.setLayout(new java.awt.CardLayout());

        CGVjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Movie Name", "Genre", "Director", "Release Year", "Movie Time"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        CGVjTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CGVjTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(CGVjTable);

        Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchActionPerformed(evt);
            }
        });
        Search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                SearchKeyReleased(evt);
            }
        });

        jLabel2.setText("Search:");

        jLabel11.setText("Movie name:");

        MovieTime.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), new java.util.Date(1681484480294L), null, java.util.Calendar.DAY_OF_MONTH));
        MovieTime.setEnabled(false);

        jLabel6.setFont(new java.awt.Font("Switzerland", 3, 14)); // NOI18N
        jLabel6.setText("Movie Information:");

        Moviename.setEditable(false);
        Moviename.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MovienameActionPerformed(evt);
            }
        });

        TicketPrice.setEditable(false);
        TicketPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TicketPriceActionPerformed(evt);
            }
        });

        jLabel7.setText("Ticket Price:");

        jLabel5.setText("Release Year:");

        SeatNumber.setEditable(false);
        SeatNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeatNumberActionPerformed(evt);
            }
        });

        jLabel8.setText("Total Seat:");

        jLabel9.setText("Director:");

        jLabel10.setText("Hall number:");

        jLabel12.setText("Genre:");

        jLabel13.setText("Movie Time:");

        Director.setEditable(false);

        Genre.setEditable(false);
        Genre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenreActionPerformed(evt);
            }
        });

        Year.setEditable(false);
        Year.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                YearActionPerformed(evt);
            }
        });

        Hall.setEditable(false);

        Purchase.setBackground(new java.awt.Color(0, 204, 0));
        Purchase.setFont(new java.awt.Font("VnArabia2", 1, 14)); // NOI18N
        Purchase.setText("Purcharse");
        Purchase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PurchaseActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        jLabel14.setText("Choose the number ticket you want to buy:");

        jLabel15.setFont(new java.awt.Font("VnBarmeno", 0, 14)); // NOI18N
        jLabel15.setText("Total Price");

        Tprice.setEditable(false);

        NSeat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NSeatMouseClicked(evt);
            }
        });
        NSeat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NSeatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BookingCGVMovieLayout = new javax.swing.GroupLayout(BookingCGVMovie);
        BookingCGVMovie.setLayout(BookingCGVMovieLayout);
        BookingCGVMovieLayout.setHorizontalGroup(
            BookingCGVMovieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BookingCGVMovieLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(BookingCGVMovieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BookingCGVMovieLayout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NSeat, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(108, 108, 108))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BookingCGVMovieLayout.createSequentialGroup()
                        .addGroup(BookingCGVMovieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Purchase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel15)
                            .addComponent(Tprice))
                        .addGap(42, 42, 42))))
            .addGroup(BookingCGVMovieLayout.createSequentialGroup()
                .addGroup(BookingCGVMovieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BookingCGVMovieLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(BookingCGVMovieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(BookingCGVMovieLayout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addGroup(BookingCGVMovieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(BookingCGVMovieLayout.createSequentialGroup()
                                        .addGroup(BookingCGVMovieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(BookingCGVMovieLayout.createSequentialGroup()
                                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(Director, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(BookingCGVMovieLayout.createSequentialGroup()
                                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(TicketPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(BookingCGVMovieLayout.createSequentialGroup()
                                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(SeatNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(12, 12, 12)
                                        .addGroup(BookingCGVMovieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(BookingCGVMovieLayout.createSequentialGroup()
                                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Moviename, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(26, 26, 26)
                                .addGroup(BookingCGVMovieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(MovieTime, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Genre)
                                    .addComponent(Year)
                                    .addComponent(Hall)))
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(BookingCGVMovieLayout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(92, Short.MAX_VALUE))
        );
        BookingCGVMovieLayout.setVerticalGroup(
            BookingCGVMovieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BookingCGVMovieLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BookingCGVMovieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(Moviename, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(Year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(BookingCGVMovieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(Director, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(Genre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BookingCGVMovieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel13)
                    .addComponent(MovieTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TicketPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(BookingCGVMovieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel8)
                    .addComponent(SeatNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Hall, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BookingCGVMovieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(NSeat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Tprice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Purchase)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout CGVmovieLayout = new javax.swing.GroupLayout(CGVmovie);
        CGVmovie.setLayout(CGVmovieLayout);
        CGVmovieLayout.setHorizontalGroup(
            CGVmovieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CGVmovieLayout.createSequentialGroup()
                .addGroup(CGVmovieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 665, Short.MAX_VALUE)
                    .addGroup(CGVmovieLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(CGVmovieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(CGVmovieLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Search, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(BookingCGVMovie, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        CGVmovieLayout.setVerticalGroup(
            CGVmovieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CGVmovieLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(CGVmovieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BookingCGVMovie, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        DisplayPanel.add(CGVmovie, "card2");

        GalaxyjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Movie Name", "Genre", "Director", "Release Year", "Movie Time"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        GalaxyjTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GalaxyjTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(GalaxyjTable);

        Search1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Search1ActionPerformed(evt);
            }
        });
        Search1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Search1KeyReleased(evt);
            }
        });

        jLabel3.setText("Search:");

        jLabel16.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        jLabel16.setText("Choose the number ticket you want to buy:");

        jLabel17.setText("Movie Time:");

        Tprice1.setEditable(false);
        Tprice1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tprice1ActionPerformed(evt);
            }
        });

        Moviename1.setEditable(false);
        Moviename1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Moviename1ActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("VnBarmeno", 0, 14)); // NOI18N
        jLabel18.setText("Total Price");

        TicketPrice1.setEditable(false);
        TicketPrice1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TicketPrice1ActionPerformed(evt);
            }
        });

        Director1.setEditable(false);

        jLabel19.setText("Ticket Price:");

        Genre1.setEditable(false);
        Genre1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Genre1ActionPerformed(evt);
            }
        });

        jLabel20.setText("Release Year:");

        Year1.setEditable(false);
        Year1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Year1ActionPerformed(evt);
            }
        });

        SeatNumber1.setEditable(false);
        SeatNumber1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeatNumber1ActionPerformed(evt);
            }
        });

        Hall1.setEditable(false);

        jLabel21.setText("Total Seat:");

        jLabel22.setText("Director:");

        jLabel23.setText("Movie name:");

        jLabel24.setText("Hall number:");

        jButton2.setBackground(new java.awt.Color(0, 204, 0));
        jButton2.setFont(new java.awt.Font("VnArabia2", 1, 14)); // NOI18N
        jButton2.setText("Purcharse");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        MovieTime1.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), new java.util.Date(1681484480294L), null, java.util.Calendar.DAY_OF_MONTH));
        MovieTime1.setEnabled(false);

        jLabel25.setText("Genre:");

        jLabel26.setFont(new java.awt.Font("Switzerland", 3, 14)); // NOI18N
        jLabel26.setText("Movie Information:");

        Nseat1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Nseat1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BookingGalaxyMovieLayout = new javax.swing.GroupLayout(BookingGalaxyMovie);
        BookingGalaxyMovie.setLayout(BookingGalaxyMovieLayout);
        BookingGalaxyMovieLayout.setHorizontalGroup(
            BookingGalaxyMovieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BookingGalaxyMovieLayout.createSequentialGroup()
                .addGroup(BookingGalaxyMovieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BookingGalaxyMovieLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(BookingGalaxyMovieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(BookingGalaxyMovieLayout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addGroup(BookingGalaxyMovieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(BookingGalaxyMovieLayout.createSequentialGroup()
                                        .addGroup(BookingGalaxyMovieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(BookingGalaxyMovieLayout.createSequentialGroup()
                                                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(Director1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(BookingGalaxyMovieLayout.createSequentialGroup()
                                                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(TicketPrice1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(BookingGalaxyMovieLayout.createSequentialGroup()
                                                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(SeatNumber1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(12, 12, 12)
                                        .addGroup(BookingGalaxyMovieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(BookingGalaxyMovieLayout.createSequentialGroup()
                                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Moviename1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(26, 26, 26)
                                .addGroup(BookingGalaxyMovieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(MovieTime1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Genre1)
                                    .addComponent(Year1)
                                    .addComponent(Hall1)))
                            .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(BookingGalaxyMovieLayout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(98, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BookingGalaxyMovieLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(BookingGalaxyMovieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BookingGalaxyMovieLayout.createSequentialGroup()
                        .addGroup(BookingGalaxyMovieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(BookingGalaxyMovieLayout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Nseat1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(51, 51, 51))
                            .addComponent(Tprice1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(67, 67, 67))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BookingGalaxyMovieLayout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addGap(80, 80, 80))
                    .addGroup(BookingGalaxyMovieLayout.createSequentialGroup()
                        .addGap(360, 360, 360)
                        .addComponent(jButton2)
                        .addContainerGap())))
        );
        BookingGalaxyMovieLayout.setVerticalGroup(
            BookingGalaxyMovieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BookingGalaxyMovieLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel26)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BookingGalaxyMovieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(Moviename1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20)
                    .addComponent(Year1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(BookingGalaxyMovieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(Director1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25)
                    .addComponent(Genre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BookingGalaxyMovieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jLabel17)
                    .addComponent(MovieTime1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TicketPrice1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(BookingGalaxyMovieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(jLabel21)
                    .addComponent(SeatNumber1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Hall1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BookingGalaxyMovieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(Nseat1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Tprice1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout GalaxymovieLayout = new javax.swing.GroupLayout(Galaxymovie);
        Galaxymovie.setLayout(GalaxymovieLayout);
        GalaxymovieLayout.setHorizontalGroup(
            GalaxymovieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GalaxymovieLayout.createSequentialGroup()
                .addGroup(GalaxymovieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(GalaxymovieLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(GalaxymovieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 659, Short.MAX_VALUE)
                            .addGroup(GalaxymovieLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Search1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(BookingGalaxyMovie, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        GalaxymovieLayout.setVerticalGroup(
            GalaxymovieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, GalaxymovieLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(GalaxymovieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Search1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BookingGalaxyMovie, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        DisplayPanel.add(Galaxymovie, "card3");

        LotteTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Movie Name", "Genre", "Director", "Release Year", "Movie Time"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        LotteTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LotteTableMouseClicked(evt);
            }
        });
        LotteTable.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                LotteTableKeyReleased(evt);
            }
        });
        jScrollPane3.setViewportView(LotteTable);

        Search2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Search2ActionPerformed(evt);
            }
        });
        Search2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Search2KeyReleased(evt);
            }
        });

        jLabel4.setText("Search:");

        jLabel27.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        jLabel27.setText("Choose the number ticket you want to buy:");

        jLabel28.setText("Movie Time:");

        Tprice2.setEditable(false);
        Tprice2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tprice2ActionPerformed(evt);
            }
        });

        Moviename2.setEditable(false);
        Moviename2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Moviename2ActionPerformed(evt);
            }
        });

        jLabel29.setFont(new java.awt.Font("VnBarmeno", 0, 14)); // NOI18N
        jLabel29.setText("Total Price");

        TicketPrice2.setEditable(false);
        TicketPrice2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TicketPrice2ActionPerformed(evt);
            }
        });

        Director2.setEditable(false);

        jLabel30.setText("Ticket Price:");

        Genre2.setEditable(false);
        Genre2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Genre2ActionPerformed(evt);
            }
        });

        jLabel31.setText("Release Year:");

        Year2.setEditable(false);
        Year2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Year2ActionPerformed(evt);
            }
        });

        SeatNumber2.setEditable(false);
        SeatNumber2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeatNumber2ActionPerformed(evt);
            }
        });

        Hall2.setEditable(false);

        jLabel32.setText("Total Seat:");

        jLabel33.setText("Director:");

        jLabel34.setText("Movie name:");

        jLabel35.setText("Hall number:");

        jButton3.setBackground(new java.awt.Color(0, 204, 0));
        jButton3.setFont(new java.awt.Font("VnArabia2", 1, 14)); // NOI18N
        jButton3.setText("Purcharse");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        MovieTime2.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), new java.util.Date(1681484480294L), null, java.util.Calendar.DAY_OF_MONTH));
        MovieTime2.setEnabled(false);

        jLabel36.setText("Genre:");

        jLabel37.setFont(new java.awt.Font("Switzerland", 3, 14)); // NOI18N
        jLabel37.setText("Movie Information:");

        Nseat2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Nseat2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BookingLooteMovieLayout = new javax.swing.GroupLayout(BookingLooteMovie);
        BookingLooteMovie.setLayout(BookingLooteMovieLayout);
        BookingLooteMovieLayout.setHorizontalGroup(
            BookingLooteMovieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BookingLooteMovieLayout.createSequentialGroup()
                .addGroup(BookingLooteMovieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BookingLooteMovieLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(BookingLooteMovieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(BookingLooteMovieLayout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addGroup(BookingLooteMovieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(BookingLooteMovieLayout.createSequentialGroup()
                                        .addGroup(BookingLooteMovieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(BookingLooteMovieLayout.createSequentialGroup()
                                                .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(Director2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(BookingLooteMovieLayout.createSequentialGroup()
                                                .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(TicketPrice2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(BookingLooteMovieLayout.createSequentialGroup()
                                                .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(SeatNumber2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(12, 12, 12)
                                        .addGroup(BookingLooteMovieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(BookingLooteMovieLayout.createSequentialGroup()
                                        .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Moviename2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(26, 26, 26)
                                .addGroup(BookingLooteMovieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(MovieTime2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Genre2)
                                    .addComponent(Year2)
                                    .addComponent(Hall2)))
                            .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(BookingLooteMovieLayout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(92, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BookingLooteMovieLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(BookingLooteMovieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BookingLooteMovieLayout.createSequentialGroup()
                        .addGroup(BookingLooteMovieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(BookingLooteMovieLayout.createSequentialGroup()
                                .addComponent(jLabel27)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Nseat2, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43))
                            .addComponent(Tprice2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(67, 67, 67))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BookingLooteMovieLayout.createSequentialGroup()
                        .addComponent(jLabel29)
                        .addGap(80, 80, 80))
                    .addGroup(BookingLooteMovieLayout.createSequentialGroup()
                        .addGap(360, 360, 360)
                        .addComponent(jButton3)
                        .addContainerGap())))
        );
        BookingLooteMovieLayout.setVerticalGroup(
            BookingLooteMovieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BookingLooteMovieLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel37)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BookingLooteMovieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34)
                    .addComponent(Moviename2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel31)
                    .addComponent(Year2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(BookingLooteMovieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33)
                    .addComponent(Director2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel36)
                    .addComponent(Genre2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BookingLooteMovieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(jLabel28)
                    .addComponent(MovieTime2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TicketPrice2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(BookingLooteMovieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel35)
                    .addComponent(jLabel32)
                    .addComponent(SeatNumber2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Hall2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BookingLooteMovieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(Nseat2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addComponent(jLabel29)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Tprice2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout LottemovieLayout = new javax.swing.GroupLayout(Lottemovie);
        Lottemovie.setLayout(LottemovieLayout);
        LottemovieLayout.setHorizontalGroup(
            LottemovieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LottemovieLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(LottemovieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BookingLooteMovie, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 659, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, LottemovieLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Search2, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        LottemovieLayout.setVerticalGroup(
            LottemovieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LottemovieLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(LottemovieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Search2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BookingLooteMovie, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        DisplayPanel.add(Lottemovie, "card4");

        getContentPane().add(DisplayPanel, java.awt.BorderLayout.CENTER);

        Cgv.setText("Cgv cinema");
        Cgv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CgvActionPerformed(evt);
            }
        });

        Galaxy.setText("Galaxy cinema");
        Galaxy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GalaxyActionPerformed(evt);
            }
        });

        Lotte.setText("Lotte cinema");
        Lotte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LotteActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 2, 18)); // NOI18N
        jLabel1.setText("Choose cinema ");

        javax.swing.GroupLayout CinemaButtonLayout = new javax.swing.GroupLayout(CinemaButton);
        CinemaButton.setLayout(CinemaButtonLayout);
        CinemaButtonLayout.setHorizontalGroup(
            CinemaButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CinemaButtonLayout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addGroup(CinemaButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(CinemaButtonLayout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(CinemaButtonLayout.createSequentialGroup()
                        .addComponent(Cgv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(92, 92, 92)
                        .addComponent(Galaxy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(15, 15, 15)))
                .addGap(84, 84, 84)
                .addComponent(Lotte, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(74, 74, 74))
        );
        CinemaButtonLayout.setVerticalGroup(
            CinemaButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CinemaButtonLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(CinemaButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cgv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Galaxy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Lotte, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30))
        );

        getContentPane().add(CinemaButton, java.awt.BorderLayout.PAGE_START);

        jMenu1.setText("Seratina");
        jMenuBar1.add(jMenu1);

        jMenu3.setText("Purchase History");

        jMenuItem2.setText("Purchase History");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem2);

        jMenuBar1.add(jMenu3);

        jMenu2.setText("Log Out");
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        jMenuItem1.setText("Log Out");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CgvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CgvActionPerformed
        DisplayPanel.removeAll();
        DisplayPanel.add(CGVmovie);
        DisplayPanel.repaint();
        DisplayPanel.validate();
    }//GEN-LAST:event_CgvActionPerformed

    private void GalaxyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GalaxyActionPerformed
        DisplayPanel.removeAll();
        DisplayPanel.add(Galaxymovie);
        DisplayPanel.repaint();
        DisplayPanel.validate();
    }//GEN-LAST:event_GalaxyActionPerformed

    private void LotteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LotteActionPerformed
        DisplayPanel.removeAll();
        DisplayPanel.add(Lottemovie);
        DisplayPanel.repaint();
        DisplayPanel.validate();
    }//GEN-LAST:event_LotteActionPerformed

    private void SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchActionPerformed

    private void SearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SearchKeyReleased
        DefaultTableModel table = (DefaultTableModel) CGVjTable.getModel();
        String search = Search.getText().trim();
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(table);
        CGVjTable.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(search));
    }//GEN-LAST:event_SearchKeyReleased

    private void Search1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Search1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Search1ActionPerformed

    private void Search1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Search1KeyReleased
        DefaultTableModel table = (DefaultTableModel) GalaxyjTable.getModel();
        String search = Search1.getText().trim();
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(table);
        GalaxyjTable.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(search));
    }//GEN-LAST:event_Search1KeyReleased

    private void Search2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Search2ActionPerformed
    
    }//GEN-LAST:event_Search2ActionPerformed

    private void Search2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Search2KeyReleased
        DefaultTableModel table = (DefaultTableModel) LotteTable.getModel();
        String search = Search2.getText().trim();
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(table);
        LotteTable.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(search));
    }//GEN-LAST:event_Search2KeyReleased

    private void LotteTableKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_LotteTableKeyReleased
        
    }//GEN-LAST:event_LotteTableKeyReleased

    private void CGVjTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CGVjTableMouseClicked
       int row = CGVjTable.getSelectedRow();
       int max=0;
       MovieController movie = new MovieController();
       DefaultTableModel table = (DefaultTableModel) CGVjTable.getModel();
        for(int i =0;i<movie.cgv.size();i++){
            if(movie.cgv.get(i).getName().equals(table.getValueAt(row, 0).toString()) && movie.cgv.get(i).getMovieTime().equals(table.getValueAt(row, 4))){
                Moviename.setText(movie.cgv.get(i).getName());
                Director.setText(movie.cgv.get(i).getDirector());
                TicketPrice.setText(movie.cgv.get(i).getTicketPrice()+"");
                SeatNumber.setText(movie.cgv.get(i).getSeatNumber()+"");
                Year.setText(movie.cgv.get(i).getReleaseYear()+"");
                Genre.setText(movie.cgv.get(i).getGenre());
                MovieTime.setValue(movie.cgv.get(i).getMovieTime());
                Hall.setText(movie.cgv.get(i).getHalls()+"");
                max = movie.cgv.get(i).getSeatNumber();
            }
        }
        String[] priceArray = new String[max];
        for(int i =0;i<max;i++){
            priceArray[i] = (i+1)+"";
        }
        NSeat.setModel(new javax.swing.DefaultComboBoxModel<>(priceArray));
        
    }//GEN-LAST:event_CGVjTableMouseClicked

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        AuthenticationController au = new AuthenticationController();
        au.deleteUserId();
        new LoginFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void MovienameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MovienameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MovienameActionPerformed

    private void TicketPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TicketPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TicketPriceActionPerformed

    private void SeatNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeatNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SeatNumberActionPerformed

    private void GenreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GenreActionPerformed

    private void YearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_YearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_YearActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void Tprice1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tprice1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Tprice1ActionPerformed

    private void Moviename1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Moviename1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Moviename1ActionPerformed

    private void TicketPrice1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TicketPrice1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TicketPrice1ActionPerformed

    private void Genre1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Genre1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Genre1ActionPerformed

    private void Year1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Year1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Year1ActionPerformed

    private void SeatNumber1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeatNumber1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SeatNumber1ActionPerformed

    private void Tprice2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tprice2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Tprice2ActionPerformed

    private void Moviename2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Moviename2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Moviename2ActionPerformed

    private void TicketPrice2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TicketPrice2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TicketPrice2ActionPerformed

    private void Genre2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Genre2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Genre2ActionPerformed

    private void Year2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Year2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Year2ActionPerformed

    private void SeatNumber2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeatNumber2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SeatNumber2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            if(Tprice2.getText().isEmpty()){
                JOptionPane.showMessageDialog(null,"Pls choose a movie and ticket number!");
            }else{
                    int row = LotteTable.getSelectedRow();
                    int selectedIndex =Integer.parseInt((String) Nseat2.getSelectedItem());
                    DefaultTableModel table = (DefaultTableModel) LotteTable.getModel();
                    BookingController booking = new BookingController();
                    int flag = booking.BookingLotteMovie(selectedIndex, row, table);
                    if (flag == 1){
                        final BookingHomeFrame Frame = new BookingHomeFrame();
                        Frame.setVisible(true);
                        Frame.repaint();
                        this.dispose();
                    }
            }
        }catch (InputMismatchException e) {
            JOptionPane.showMessageDialog(null,"Invalid input format! Please enter the valid data.");
        }catch (Exception f){
            JOptionPane.showMessageDialog(null, "Error");
            System.out.println(f.getMessage());
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void PurchaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PurchaseActionPerformed
        try {
            if(Tprice.getText().isEmpty()){
                JOptionPane.showMessageDialog(null,"Pls choose a movie and ticket number!");
            }else{
                    int row = CGVjTable.getSelectedRow();
                    int selectedIndex =Integer.parseInt((String) NSeat.getSelectedItem());
                    DefaultTableModel table = (DefaultTableModel) CGVjTable.getModel();
                    BookingController booking = new BookingController();
                    int flag = booking.BookingCGVMovie(selectedIndex, row, table);
                    if (flag == 1){
                        final BookingHomeFrame Frame = new BookingHomeFrame();
                        Frame.setVisible(true);
                        Frame.repaint();
                        this.dispose();
                    }
            }
        }catch (InputMismatchException e) {
            JOptionPane.showMessageDialog(null,"Invalid input format! Please enter the valid data.");
        }catch (Exception f){
            JOptionPane.showMessageDialog(null, "Error");
            System.out.println(f.getMessage());
        }
    }//GEN-LAST:event_PurchaseActionPerformed

    private void LotteTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LotteTableMouseClicked
        int max=0;
        int row = LotteTable.getSelectedRow();
        MovieController movie = new MovieController();
        DefaultTableModel table = (DefaultTableModel) LotteTable.getModel();
        for(int i =0;i<movie.lotte.size();i++){
            if(movie.lotte.get(i).getName().equals(table.getValueAt(row, 0).toString()) && movie.lotte.get(i).getMovieTime().equals(table.getValueAt(row, 4))){
                Moviename2.setText(movie.lotte.get(i).getName());
                Director2.setText(movie.lotte.get(i).getDirector());
                TicketPrice2.setText(movie.lotte.get(i).getTicketPrice()+"");
                SeatNumber2.setText(movie.lotte.get(i).getSeatNumber()+"");
                Year2.setText(movie.lotte.get(i).getReleaseYear()+"");
                Genre2.setText(movie.lotte.get(i).getGenre());
                MovieTime2.setValue(movie.lotte.get(i).getMovieTime());
                Hall2.setText(movie.lotte.get(i).getHalls()+"");
                max = movie.lotte.get(i).getSeatNumber();
            }
        }
        String[] priceArray = new String[max];
        for(int i =0;i<max;i++){
            priceArray[i] = (i+1)+"";
        }
        Nseat2.setModel(new javax.swing.DefaultComboBoxModel<>(priceArray));
    }//GEN-LAST:event_LotteTableMouseClicked

    private void GalaxyjTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GalaxyjTableMouseClicked
        int max=0;
        int row = GalaxyjTable.getSelectedRow();
        MovieController movie = new MovieController();
        DefaultTableModel table = (DefaultTableModel) GalaxyjTable.getModel();
        for(int i =0;i<movie.galaxy.size();i++){
            if(movie.galaxy.get(i).getName().equals(table.getValueAt(row, 0).toString()) && movie.galaxy.get(i).getMovieTime().equals(table.getValueAt(row, 4))){
                Moviename1.setText(movie.galaxy.get(i).getName());
                Director1.setText(movie.galaxy.get(i).getDirector());
                TicketPrice1.setText(movie.galaxy.get(i).getTicketPrice()+"");
                SeatNumber1.setText(movie.galaxy.get(i).getSeatNumber()+"");
                Year1.setText(movie.galaxy.get(i).getReleaseYear()+"");
                Genre1.setText(movie.galaxy.get(i).getGenre());
                MovieTime1.setValue(movie.galaxy.get(i).getMovieTime());
                Hall1.setText(movie.galaxy.get(i).getHalls()+"");
                max = movie.galaxy.get(i).getSeatNumber();
            }
        }
        String[] priceArray = new String[max];
        for(int i =0;i<max;i++){
            priceArray[i] = (i+1)+"";
        }
        Nseat1.setModel(new javax.swing.DefaultComboBoxModel<>(priceArray));
    }//GEN-LAST:event_GalaxyjTableMouseClicked

    private void NSeatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NSeatActionPerformed
        int selectedIndex =Integer.parseInt((String) NSeat.getSelectedItem());
        MovieController movie = new MovieController();
        int row = CGVjTable.getSelectedRow();
        DefaultTableModel table = (DefaultTableModel) CGVjTable.getModel();
        BookingController booking = new BookingController();
        double price=0;
        for(int i =0;i<movie.cgv.size();i++){
            if(movie.cgv.get(i).getName().equals(table.getValueAt(row, 0).toString()) && movie.cgv.get(i).getMovieTime().equals(table.getValueAt(row, 4))){
                price = movie.cgv.get(i).getTicketPrice();
            }
        }
        if(selectedIndex>0){
            Tprice.setText(booking.totalprice(selectedIndex, price)+"");
        }else{
            JOptionPane.showMessageDialog(null,"Error!");
        }
        

    }//GEN-LAST:event_NSeatActionPerformed

    private void NSeatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NSeatMouseClicked
        
        
    }//GEN-LAST:event_NSeatMouseClicked

    private void Nseat1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Nseat1ActionPerformed
        int selectedIndex =Integer.parseInt((String) Nseat1.getSelectedItem());
        MovieController movie = new MovieController();
        int row = GalaxyjTable.getSelectedRow();
        DefaultTableModel table = (DefaultTableModel) GalaxyjTable.getModel();
        BookingController booking = new BookingController();
        double price=0;
        for(int i =0;i<movie.galaxy.size();i++){
            if(movie.galaxy.get(i).getName().equals(table.getValueAt(row, 0).toString()) && movie.galaxy.get(i).getMovieTime().equals(table.getValueAt(row, 4))){
                price = movie.galaxy.get(i).getTicketPrice();
            }
        }
        if(selectedIndex>0){
            Tprice1.setText(booking.totalprice(selectedIndex, price)+"");
        }else{
            JOptionPane.showMessageDialog(null,"Error!");
        }
    }//GEN-LAST:event_Nseat1ActionPerformed

    private void Nseat2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Nseat2ActionPerformed
        int selectedIndex =Integer.parseInt((String) Nseat2.getSelectedItem());
        MovieController movie = new MovieController();
        int row = LotteTable.getSelectedRow();
        DefaultTableModel table = (DefaultTableModel) LotteTable.getModel();
        BookingController booking = new BookingController();
        double price=0;
        for(int i =0;i<movie.lotte.size();i++){
            if(movie.lotte.get(i).getName().equals(table.getValueAt(row, 0).toString()) && movie.lotte.get(i).getMovieTime().equals(table.getValueAt(row, 4))){
                price = movie.lotte.get(i).getTicketPrice();
            }
        }
        if(selectedIndex>0){
            Tprice2.setText(booking.totalprice(selectedIndex, price)+"");
        }else{
            JOptionPane.showMessageDialog(null,"Error!");
        }
    }//GEN-LAST:event_Nseat2ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            if(Tprice1.getText().isEmpty()){
                JOptionPane.showMessageDialog(null,"Pls choose a movie and ticket number!");
            }else{
                    int row = GalaxyjTable.getSelectedRow();
                    int selectedIndex =Integer.parseInt((String) Nseat1.getSelectedItem());
                    DefaultTableModel table = (DefaultTableModel) GalaxyjTable.getModel();
                    BookingController booking = new BookingController();
                    int flag = booking.BookingGalaxyMovie(selectedIndex, row, table);
                    if (flag == 1){
                        final BookingHomeFrame Frame = new BookingHomeFrame();
                        Frame.setVisible(true);
                        Frame.repaint();
                        this.dispose();
                    }
            }
        }catch (InputMismatchException e) {
            JOptionPane.showMessageDialog(null,"Invalid input format! Please enter the valid data.");
        }catch (Exception f){
            JOptionPane.showMessageDialog(null, "Error");
            System.out.println(f.getMessage());
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu2ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        new PurchaseHistoryFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BookingHomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BookingHomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BookingHomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BookingHomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BookingHomeFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BookingCGVMovie;
    private javax.swing.JPanel BookingGalaxyMovie;
    private javax.swing.JPanel BookingLooteMovie;
    private javax.swing.JTable CGVjTable;
    private javax.swing.JPanel CGVmovie;
    private javax.swing.JButton Cgv;
    private javax.swing.JPanel CinemaButton;
    private javax.swing.JTextField Director;
    private javax.swing.JTextField Director1;
    private javax.swing.JTextField Director2;
    private javax.swing.JPanel DisplayPanel;
    private javax.swing.JButton Galaxy;
    private javax.swing.JTable GalaxyjTable;
    private javax.swing.JPanel Galaxymovie;
    private javax.swing.JTextField Genre;
    private javax.swing.JTextField Genre1;
    private javax.swing.JTextField Genre2;
    private javax.swing.JTextField Hall;
    private javax.swing.JTextField Hall1;
    private javax.swing.JTextField Hall2;
    private javax.swing.JButton Lotte;
    private javax.swing.JTable LotteTable;
    private javax.swing.JPanel Lottemovie;
    private javax.swing.JSpinner MovieTime;
    private javax.swing.JSpinner MovieTime1;
    private javax.swing.JSpinner MovieTime2;
    private javax.swing.JTextField Moviename;
    private javax.swing.JTextField Moviename1;
    private javax.swing.JTextField Moviename2;
    private javax.swing.JComboBox<String> NSeat;
    private javax.swing.JComboBox<String> Nseat1;
    private javax.swing.JComboBox<String> Nseat2;
    private javax.swing.JButton Purchase;
    private javax.swing.JTextField Search;
    private javax.swing.JTextField Search1;
    private javax.swing.JTextField Search2;
    private javax.swing.JTextField SeatNumber;
    private javax.swing.JTextField SeatNumber1;
    private javax.swing.JTextField SeatNumber2;
    private javax.swing.JTextField TicketPrice;
    private javax.swing.JTextField TicketPrice1;
    private javax.swing.JTextField TicketPrice2;
    private javax.swing.JTextField Tprice;
    private javax.swing.JTextField Tprice1;
    private javax.swing.JTextField Tprice2;
    private javax.swing.JTextField Year;
    private javax.swing.JTextField Year1;
    private javax.swing.JTextField Year2;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    // End of variables declaration//GEN-END:variables
}
