/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.moviebooking;
import java.util.Date;
import java.util.InputMismatchException;
import javax.swing.*;
/**
 *
 * @author ADMIN
 */
public class EditmovieFrame extends javax.swing.JFrame {
    
    /**
     * Creates new form movieFrame
     */
    public EditmovieFrame() {
        initComponents();
        MovieController movie = new MovieController();
        String[] cgvArray = new String[movie.cgv.size()];
        for(int i =0;i<movie.cgv.size();i++){
            cgvArray[i] = movie.cgv.get(i).getName();
        }
        moviesInCgv.setModel(new javax.swing.DefaultComboBoxModel<>(cgvArray));
        moviesInCgv.setSelectedIndex(0);
        String[] galaxyArray = new String[movie.galaxy.size()];
        for(int i =0;i<movie.galaxy.size();i++){
            galaxyArray[i] = movie.galaxy.get(i).getName();
        }
        moviesInGalaxy.setModel(new javax.swing.DefaultComboBoxModel<>(galaxyArray));
        moviesInGalaxy.setSelectedIndex(0);
        String[] lotteArray = new String[movie.lotte.size()];
        for(int i =0;i<movie.lotte.size();i++){
            lotteArray[i] = movie.lotte.get(i).getName();
        }
        moviesInLotte.setModel(new javax.swing.DefaultComboBoxModel<>(lotteArray));
        moviesInLotte.setSelectedIndex(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CinemaButton = new javax.swing.JPanel();
        Cgv = new javax.swing.JButton();
        Galaxy = new javax.swing.JButton();
        Lotte = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        MainPanel = new javax.swing.JPanel();
        CGVmovie = new javax.swing.JPanel();
        Year = new javax.swing.JSpinner();
        HallNumber = new javax.swing.JSpinner();
        jLabel11 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Moviename = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        Director = new javax.swing.JTextField();
        MovieTime = new javax.swing.JSpinner();
        Genre = new javax.swing.JComboBox<>();
        TicketPrice = new javax.swing.JTextField();
        Edit = new javax.swing.JButton();
        SeatNumber = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        moviesInCgv = new javax.swing.JComboBox<>();
        Delete = new javax.swing.JButton();
        Galaxymovie = new javax.swing.JPanel();
        Year1 = new javax.swing.JSpinner();
        HallNumber1 = new javax.swing.JSpinner();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        Moviename1 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        Director1 = new javax.swing.JTextField();
        MovieTime1 = new javax.swing.JSpinner();
        Genre1 = new javax.swing.JComboBox<>();
        TicketPrice1 = new javax.swing.JTextField();
        SeatNumber1 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        moviesInGalaxy = new javax.swing.JComboBox<>();
        Delete1 = new javax.swing.JButton();
        Edit1 = new javax.swing.JButton();
        Lottemovie = new javax.swing.JPanel();
        Year2 = new javax.swing.JSpinner();
        HallNumber2 = new javax.swing.JSpinner();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        Moviename2 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        Director2 = new javax.swing.JTextField();
        MovieTime2 = new javax.swing.JSpinner();
        Genre2 = new javax.swing.JComboBox<>();
        TicketPrice2 = new javax.swing.JTextField();
        SeatNumber2 = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        moviesInLotte = new javax.swing.JComboBox<>();
        Delete2 = new javax.swing.JButton();
        Edit2 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Edit Movie");

        Cgv.setText("Cgv cinema");
        Cgv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CgvActionPerformed(evt);
            }
        });

        Galaxy.setText("Galaxy cinema");
        Galaxy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GalaxyActionPerformed(evt);
            }
        });

        Lotte.setText("Lotte cinema");
        Lotte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LotteActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 2, 14)); // NOI18N
        jLabel1.setText("Choose cinema to edit");

        javax.swing.GroupLayout CinemaButtonLayout = new javax.swing.GroupLayout(CinemaButton);
        CinemaButton.setLayout(CinemaButtonLayout);
        CinemaButtonLayout.setHorizontalGroup(
            CinemaButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CinemaButtonLayout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(Cgv)
                .addGap(80, 80, 80)
                .addComponent(Galaxy)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addComponent(Lotte)
                .addGap(74, 74, 74))
            .addGroup(CinemaButtonLayout.createSequentialGroup()
                .addGap(231, 231, 231)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        CinemaButtonLayout.setVerticalGroup(
            CinemaButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CinemaButtonLayout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(CinemaButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cgv)
                    .addComponent(Galaxy)
                    .addComponent(Lotte))
                .addGap(30, 30, 30))
        );

        getContentPane().add(CinemaButton, java.awt.BorderLayout.PAGE_START);

        MainPanel.setLayout(new java.awt.CardLayout());

        Year.setModel(new javax.swing.SpinnerNumberModel(2023, 1800, 9999, 1));

        HallNumber.setModel(new javax.swing.SpinnerNumberModel(1, 1, 8, 1));

        jLabel11.setText("Movie name:");

        jLabel6.setFont(new java.awt.Font("Switzerland", 3, 14)); // NOI18N
        jLabel6.setText("Movie Information:");

        Moviename.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MovienameActionPerformed(evt);
            }
        });

        jLabel7.setText("Ticket Price:");

        jLabel2.setText("Release Year:");

        jLabel8.setText("Total Seat:");

        jLabel3.setText("Director:");

        jLabel9.setText("Hall number:");

        jLabel4.setText("Genre:");

        jLabel10.setText("Movie Time:");

        MovieTime.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), new java.util.Date(), null, java.util.Calendar.DAY_OF_MONTH));

        Genre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Action", "Adventure", "Comedy", "Fantasy", "Historical", "Horror", "Romance", "Documentary", "Animation" }));

        TicketPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TicketPriceActionPerformed(evt);
            }
        });

        Edit.setBackground(new java.awt.Color(0, 204, 51));
        Edit.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        Edit.setText("Edit");
        Edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditActionPerformed(evt);
            }
        });

        SeatNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeatNumberActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        jLabel12.setText("Choose movie to edit:");

        moviesInCgv.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "none" }));
        moviesInCgv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moviesInCgvActionPerformed(evt);
            }
        });

        Delete.setBackground(new java.awt.Color(255, 0, 0));
        Delete.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        Delete.setText("Delete");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CGVmovieLayout = new javax.swing.GroupLayout(CGVmovie);
        CGVmovie.setLayout(CGVmovieLayout);
        CGVmovieLayout.setHorizontalGroup(
            CGVmovieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CGVmovieLayout.createSequentialGroup()
                .addGroup(CGVmovieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CGVmovieLayout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addGroup(CGVmovieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(CGVmovieLayout.createSequentialGroup()
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Moviename, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(CGVmovieLayout.createSequentialGroup()
                                .addGroup(CGVmovieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(CGVmovieLayout.createSequentialGroup()
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Director, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(CGVmovieLayout.createSequentialGroup()
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(TicketPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(CGVmovieLayout.createSequentialGroup()
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(SeatNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(12, 12, 12)
                                .addGroup(CGVmovieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(CGVmovieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CGVmovieLayout.createSequentialGroup()
                                        .addGap(28, 28, 28)
                                        .addComponent(Edit)
                                        .addGap(30, 30, 30)
                                        .addComponent(Delete)
                                        .addGap(9, 9, 9))
                                    .addGroup(CGVmovieLayout.createSequentialGroup()
                                        .addGap(36, 36, 36)
                                        .addGroup(CGVmovieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(Genre, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Year, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(MovieTime, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(HallNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(CGVmovieLayout.createSequentialGroup()
                                .addGap(137, 137, 137)
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(moviesInCgv, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(CGVmovieLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        CGVmovieLayout.setVerticalGroup(
            CGVmovieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CGVmovieLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(CGVmovieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(moviesInCgv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addGroup(CGVmovieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CGVmovieLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(CGVmovieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(Moviename, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(Year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(CGVmovieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(Director, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(Genre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(CGVmovieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel10)
                            .addComponent(MovieTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TicketPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(CGVmovieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8)
                            .addComponent(SeatNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(HallNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(67, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CGVmovieLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(CGVmovieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Edit)
                            .addComponent(Delete))
                        .addGap(24, 24, 24))))
        );

        MainPanel.add(CGVmovie, "card2");

        Year1.setModel(new javax.swing.SpinnerNumberModel(2023, 1800, 9999, 1));

        HallNumber1.setModel(new javax.swing.SpinnerNumberModel(1, 1, 8, 1));

        jLabel13.setText("Movie name:");

        jLabel14.setFont(new java.awt.Font("Switzerland", 3, 14)); // NOI18N
        jLabel14.setText("Movie Information:");

        Moviename1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Moviename1ActionPerformed(evt);
            }
        });

        jLabel15.setText("Ticket Price:");

        jLabel5.setText("Release Year:");

        jLabel16.setText("Total Seat:");

        jLabel17.setText("Director:");

        jLabel18.setText("Hall number:");

        jLabel19.setText("Genre:");

        jLabel20.setText("Movie Time:");

        MovieTime1.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), new java.util.Date(), null, java.util.Calendar.DAY_OF_MONTH));

        Genre1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Action", "Adventure", "Comedy", "Fantasy", "Historical", "Horror", "Romance", "Documentary", "Animation" }));

        TicketPrice1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TicketPrice1ActionPerformed(evt);
            }
        });

        SeatNumber1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeatNumber1ActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        jLabel21.setText("Choose movie to edit:");

        moviesInGalaxy.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        moviesInGalaxy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moviesInGalaxyActionPerformed(evt);
            }
        });

        Delete1.setBackground(new java.awt.Color(255, 0, 0));
        Delete1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        Delete1.setText("Delete");
        Delete1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Delete1ActionPerformed(evt);
            }
        });

        Edit1.setBackground(new java.awt.Color(0, 204, 51));
        Edit1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        Edit1.setText("Edit");
        Edit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Edit1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout GalaxymovieLayout = new javax.swing.GroupLayout(Galaxymovie);
        Galaxymovie.setLayout(GalaxymovieLayout);
        GalaxymovieLayout.setHorizontalGroup(
            GalaxymovieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GalaxymovieLayout.createSequentialGroup()
                .addGroup(GalaxymovieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(GalaxymovieLayout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addGroup(GalaxymovieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(GalaxymovieLayout.createSequentialGroup()
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Moviename1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(GalaxymovieLayout.createSequentialGroup()
                                .addGap(137, 137, 137)
                                .addComponent(jLabel21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(moviesInGalaxy, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(GalaxymovieLayout.createSequentialGroup()
                                .addGroup(GalaxymovieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(GalaxymovieLayout.createSequentialGroup()
                                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Director1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(GalaxymovieLayout.createSequentialGroup()
                                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(TicketPrice1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(GalaxymovieLayout.createSequentialGroup()
                                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(SeatNumber1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(12, 12, 12)
                                .addGroup(GalaxymovieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(36, 36, 36)
                                .addGroup(GalaxymovieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(GalaxymovieLayout.createSequentialGroup()
                                        .addComponent(Edit1)
                                        .addGap(30, 30, 30)
                                        .addComponent(Delete1))
                                    .addGroup(GalaxymovieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(Genre1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Year1)
                                        .addComponent(MovieTime1, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                        .addComponent(HallNumber1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(GalaxymovieLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        GalaxymovieLayout.setVerticalGroup(
            GalaxymovieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GalaxymovieLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(GalaxymovieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(moviesInGalaxy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(GalaxymovieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(Moviename1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(Year1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(GalaxymovieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(Director1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19)
                    .addComponent(Genre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(GalaxymovieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel20)
                    .addComponent(MovieTime1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TicketPrice1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(GalaxymovieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jLabel16)
                    .addComponent(SeatNumber1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HallNumber1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(GalaxymovieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Edit1)
                    .addComponent(Delete1))
                .addGap(20, 20, 20))
        );

        MainPanel.add(Galaxymovie, "card2");

        Year2.setModel(new javax.swing.SpinnerNumberModel(2023, 1800, 9999, 1));

        HallNumber2.setModel(new javax.swing.SpinnerNumberModel(1, 1, 8, 1));

        jLabel22.setText("Movie name:");

        jLabel23.setFont(new java.awt.Font("Switzerland", 3, 14)); // NOI18N
        jLabel23.setText("Movie Information:");

        Moviename2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Moviename2ActionPerformed(evt);
            }
        });

        jLabel24.setText("Ticket Price:");

        jLabel25.setText("Release Year:");

        jLabel26.setText("Total Seat:");

        jLabel27.setText("Director:");

        jLabel28.setText("Hall number:");

        jLabel29.setText("Genre:");

        jLabel30.setText("Movie Time:");

        MovieTime2.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), new java.util.Date(), null, java.util.Calendar.DAY_OF_MONTH));

        Genre2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Action", "Adventure", "Comedy", "Fantasy", "Historical", "Horror", "Romance", "Documentary", "Animation" }));

        TicketPrice2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TicketPrice2ActionPerformed(evt);
            }
        });

        SeatNumber2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeatNumber2ActionPerformed(evt);
            }
        });

        jLabel31.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        jLabel31.setText("Choose movie to edit:");

        moviesInLotte.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        moviesInLotte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moviesInLotteActionPerformed(evt);
            }
        });

        Delete2.setBackground(new java.awt.Color(255, 0, 0));
        Delete2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        Delete2.setText("Delete");
        Delete2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Delete2ActionPerformed(evt);
            }
        });

        Edit2.setBackground(new java.awt.Color(0, 204, 51));
        Edit2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        Edit2.setText("Edit");
        Edit2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Edit2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout LottemovieLayout = new javax.swing.GroupLayout(Lottemovie);
        Lottemovie.setLayout(LottemovieLayout);
        LottemovieLayout.setHorizontalGroup(
            LottemovieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LottemovieLayout.createSequentialGroup()
                .addGroup(LottemovieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LottemovieLayout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addGroup(LottemovieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(LottemovieLayout.createSequentialGroup()
                                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Moviename2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(LottemovieLayout.createSequentialGroup()
                                .addGap(137, 137, 137)
                                .addComponent(jLabel31)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(moviesInLotte, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(LottemovieLayout.createSequentialGroup()
                                .addGroup(LottemovieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(LottemovieLayout.createSequentialGroup()
                                        .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Director2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(LottemovieLayout.createSequentialGroup()
                                        .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(TicketPrice2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(LottemovieLayout.createSequentialGroup()
                                        .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(SeatNumber2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(12, 12, 12)
                                .addGroup(LottemovieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(36, 36, 36)
                                .addGroup(LottemovieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(LottemovieLayout.createSequentialGroup()
                                        .addComponent(Edit2)
                                        .addGap(30, 30, 30)
                                        .addComponent(Delete2))
                                    .addGroup(LottemovieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(Genre2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Year2)
                                        .addComponent(MovieTime2, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                        .addComponent(HallNumber2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(LottemovieLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        LottemovieLayout.setVerticalGroup(
            LottemovieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LottemovieLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(LottemovieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(moviesInLotte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(LottemovieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(Moviename2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25)
                    .addComponent(Year2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(LottemovieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(Director2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29)
                    .addComponent(Genre2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(LottemovieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(jLabel30)
                    .addComponent(MovieTime2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TicketPrice2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(LottemovieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(jLabel26)
                    .addComponent(SeatNumber2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HallNumber2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(LottemovieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Edit2)
                    .addComponent(Delete2))
                .addGap(16, 16, 16))
        );

        MainPanel.add(Lottemovie, "card2");

        getContentPane().add(MainPanel, java.awt.BorderLayout.CENTER);

        jMenu1.setText("Seratina");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");

        jMenuItem1.setText("Edit Movie");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuItem2.setText("Add Movie");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Log out");
        jMenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu3ActionPerformed(evt);
            }
        });

        jMenuItem3.setText("Log out");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem3);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MovienameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MovienameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MovienameActionPerformed

    private void TicketPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TicketPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TicketPriceActionPerformed

    private void EditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditActionPerformed
        try {
            if(Moviename.getText().isEmpty()||Director.getText().isEmpty()||TicketPrice.getText().isEmpty()|| SeatNumber.getText().isEmpty()){
                JOptionPane.showMessageDialog(null,"Pls enter all fields!");
            }else{
                    MovieController movie = new MovieController();
                    int selectedIndex = moviesInCgv.getSelectedIndex();
                    String name = Moviename.getText().trim();
                    String director = Director.getText().trim();
                    int year = (int) Year.getValue();
                    Double ticketPrice = Double.parseDouble(TicketPrice.getText().trim());
                    Date movieTime = (Date) MovieTime.getValue();
                    int seatNumber = Integer.parseInt(SeatNumber.getText().trim());
                    String genre = (String) Genre.getSelectedItem();
                    int halls = (int) HallNumber.getValue();
                    int flag = movie.editCGVMovie(selectedIndex, name, director, year, ticketPrice, movieTime, seatNumber, genre, halls);
                    if(flag==1){
                        final EditmovieFrame editFrame = new EditmovieFrame();
                        editFrame.setVisible(true);
                        editFrame.repaint();
                        this.dispose();
                    }
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null,"Invalid input format! Please enter the valid data.");
        } catch (Exception f){
            JOptionPane.showMessageDialog(null, "Error");
            System.out.println(f.getMessage());
        }
    }//GEN-LAST:event_EditActionPerformed

    private void SeatNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeatNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SeatNumberActionPerformed

    private void Moviename1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Moviename1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Moviename1ActionPerformed

    private void TicketPrice1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TicketPrice1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TicketPrice1ActionPerformed

    private void SeatNumber1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeatNumber1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SeatNumber1ActionPerformed

    private void Moviename2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Moviename2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Moviename2ActionPerformed

    private void TicketPrice2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TicketPrice2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TicketPrice2ActionPerformed

    private void SeatNumber2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeatNumber2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SeatNumber2ActionPerformed

    private void moviesInLotteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moviesInLotteActionPerformed
        MovieController movie = new MovieController();
        int selectedIndex = moviesInLotte.getSelectedIndex();
        Moviename2.setText(movie.lotte.get(selectedIndex).getName());
        Director2.setText(movie.lotte.get(selectedIndex).getDirector());
        TicketPrice2.setText(movie.lotte.get(selectedIndex).getTicketPrice()+"");
        SeatNumber2.setText(movie.lotte.get(selectedIndex).getSeatNumber()+"");
        Year2.setValue(movie.lotte.get(selectedIndex).getReleaseYear());
        Genre2.setSelectedItem(movie.lotte.get(selectedIndex).getGenre());
        MovieTime2.setValue(movie.lotte.get(selectedIndex).getMovieTime());
        HallNumber2.setValue(movie.lotte.get(selectedIndex).getHalls());
    }//GEN-LAST:event_moviesInLotteActionPerformed

    private void moviesInCgvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moviesInCgvActionPerformed
        MovieController movie = new MovieController();
        int selectedIndex = moviesInCgv.getSelectedIndex();
        Moviename.setText(movie.cgv.get(selectedIndex).getName());
        Director.setText(movie.cgv.get(selectedIndex).getDirector());
        TicketPrice.setText(movie.cgv.get(selectedIndex).getTicketPrice()+"");
        SeatNumber.setText(movie.cgv.get(selectedIndex).getSeatNumber()+"");
        Year.setValue(movie.cgv.get(selectedIndex).getReleaseYear());
        Genre.setSelectedItem(movie.cgv.get(selectedIndex).getGenre());
        MovieTime.setValue(movie.cgv.get(selectedIndex).getMovieTime());
        HallNumber.setValue(movie.cgv.get(selectedIndex).getHalls());
    }//GEN-LAST:event_moviesInCgvActionPerformed

    private void moviesInGalaxyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moviesInGalaxyActionPerformed
        MovieController movie = new MovieController();
        int selectedIndex = moviesInGalaxy.getSelectedIndex();
        Moviename1.setText(movie.galaxy.get(selectedIndex).getName());
        Director1.setText(movie.galaxy.get(selectedIndex).getDirector());
        TicketPrice1.setText(movie.galaxy.get(selectedIndex).getTicketPrice()+"");
        SeatNumber1.setText(movie.galaxy.get(selectedIndex).getSeatNumber()+"");
        Year1.setValue(movie.galaxy.get(selectedIndex).getReleaseYear());
        Genre1.setSelectedItem(movie.galaxy.get(selectedIndex).getGenre());
        MovieTime1.setValue(movie.galaxy.get(selectedIndex).getMovieTime());
        HallNumber1.setValue(movie.galaxy.get(selectedIndex).getHalls());
    }//GEN-LAST:event_moviesInGalaxyActionPerformed

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        MovieController movie = new MovieController();
        int selectedIndex = moviesInCgv.getSelectedIndex();
        movie.deleteCGVMovie(selectedIndex);
        final EditmovieFrame editFrame = new EditmovieFrame();
        editFrame.setVisible(true);
        editFrame.repaint();
        this.dispose();
    }//GEN-LAST:event_DeleteActionPerformed

    private void Delete1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Delete1ActionPerformed
        MovieController movie = new MovieController();
        int selectedIndex = moviesInGalaxy.getSelectedIndex();
        movie.deleteGalaxyMovie(selectedIndex);
        final EditmovieFrame editFrame = new EditmovieFrame();
        editFrame.setVisible(true);
        editFrame.repaint();
        this.dispose();
    }//GEN-LAST:event_Delete1ActionPerformed

    private void Edit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Edit1ActionPerformed
        try {
            if(Moviename1.getText().isEmpty()||Director1.getText().isEmpty()||TicketPrice1.getText().isEmpty()|| SeatNumber1.getText().isEmpty()){
                JOptionPane.showMessageDialog(null,"Pls enter all fields!");
            }else{
                    MovieController movie = new MovieController();
                    int selectedIndex = moviesInGalaxy.getSelectedIndex();
                    String name = Moviename1.getText().trim();
                    String director = Director1.getText().trim();
                    int year = (int) Year1.getValue();
                    Double ticketPrice = Double.parseDouble(TicketPrice1.getText().trim());
                    Date movieTime = (Date) MovieTime1.getValue();
                    int seatNumber = Integer.parseInt(SeatNumber1.getText().trim());
                    String genre = (String) Genre1.getSelectedItem();
                    int halls = (int) HallNumber1.getValue();
                    int flag= movie.editGalaxyMovie(selectedIndex, name, director, year, ticketPrice, movieTime, seatNumber, genre, halls);
                    if(flag==1){
                        final EditmovieFrame editFrame = new EditmovieFrame();
                        editFrame.setVisible(true);
                        editFrame.repaint();
                        this.dispose();
                    }
                    
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null,"Invalid input format! Please enter the valid data.");
        } catch (Exception f){
            JOptionPane.showMessageDialog(null, "Error");
            System.out.println(f.getMessage());
        }
    }//GEN-LAST:event_Edit1ActionPerformed

    private void Delete2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Delete2ActionPerformed
        MovieController movie = new MovieController();
        int selectedIndex = moviesInLotte.getSelectedIndex();
        movie.deleteLotteMovie(selectedIndex);
        final EditmovieFrame editFrame = new EditmovieFrame();
        editFrame.setVisible(true);
        editFrame.repaint();
        this.dispose();
    }//GEN-LAST:event_Delete2ActionPerformed

    private void Edit2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Edit2ActionPerformed
        try {
            if(Moviename2.getText().isEmpty()||Director2.getText().isEmpty()||TicketPrice2.getText().isEmpty()|| SeatNumber2.getText().isEmpty()){
                JOptionPane.showMessageDialog(null,"Pls enter all fields!");
            }else{
                    MovieController movie = new MovieController();
                    int selectedIndex = moviesInLotte.getSelectedIndex();
                    String name = Moviename2.getText().trim();
                    String director = Director2.getText().trim();
                    int year = (int) Year2.getValue();
                    Double ticketPrice = Double.parseDouble(TicketPrice2.getText().trim());
                    Date movieTime = (Date) MovieTime2.getValue();
                    int seatNumber = Integer.parseInt(SeatNumber2.getText().trim());
                    String genre = (String) Genre2.getSelectedItem();
                    int halls = (int) HallNumber2.getValue();
                    int flag = movie.editLotteMovie(selectedIndex, name, director, year, ticketPrice, movieTime, seatNumber, genre, halls);
                    if(flag==1){
                        final EditmovieFrame editFrame = new EditmovieFrame();
                        editFrame.setVisible(true);
                        editFrame.repaint();
                        this.dispose();
                    }
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null,"Invalid input format! Please enter the valid data.");
        } catch (Exception f){
            JOptionPane.showMessageDialog(null, "Error");
            System.out.println(f.getMessage());
        }
    }//GEN-LAST:event_Edit2ActionPerformed

    private void LotteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LotteActionPerformed
        MainPanel.removeAll();
        MainPanel.add(Lottemovie);
        MainPanel.repaint();
        MainPanel.validate();
    }//GEN-LAST:event_LotteActionPerformed

    private void GalaxyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GalaxyActionPerformed
        MainPanel.removeAll();
        MainPanel.add(Galaxymovie);
        MainPanel.repaint();
        MainPanel.validate();
    }//GEN-LAST:event_GalaxyActionPerformed

    private void CgvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CgvActionPerformed
        MainPanel.removeAll();
        MainPanel.add(CGVmovie);
        MainPanel.repaint();
        MainPanel.validate();
    }//GEN-LAST:event_CgvActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        new EditmovieFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        new AddmovieFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu3ActionPerformed

    }//GEN-LAST:event_jMenu3ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        new LoginFrame().setVisible(true);
        this.dispose();
        JOptionPane.showMessageDialog(null,"Log out Successfull!");
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditmovieFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditmovieFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditmovieFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditmovieFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditmovieFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CGVmovie;
    private javax.swing.JButton Cgv;
    private javax.swing.JPanel CinemaButton;
    private javax.swing.JButton Delete;
    private javax.swing.JButton Delete1;
    private javax.swing.JButton Delete2;
    private javax.swing.JTextField Director;
    private javax.swing.JTextField Director1;
    private javax.swing.JTextField Director2;
    private javax.swing.JButton Edit;
    private javax.swing.JButton Edit1;
    private javax.swing.JButton Edit2;
    private javax.swing.JButton Galaxy;
    private javax.swing.JPanel Galaxymovie;
    private javax.swing.JComboBox<String> Genre;
    private javax.swing.JComboBox<String> Genre1;
    private javax.swing.JComboBox<String> Genre2;
    private javax.swing.JSpinner HallNumber;
    private javax.swing.JSpinner HallNumber1;
    private javax.swing.JSpinner HallNumber2;
    private javax.swing.JButton Lotte;
    private javax.swing.JPanel Lottemovie;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JSpinner MovieTime;
    private javax.swing.JSpinner MovieTime1;
    private javax.swing.JSpinner MovieTime2;
    private javax.swing.JTextField Moviename;
    private javax.swing.JTextField Moviename1;
    private javax.swing.JTextField Moviename2;
    private javax.swing.JTextField SeatNumber;
    private javax.swing.JTextField SeatNumber1;
    private javax.swing.JTextField SeatNumber2;
    private javax.swing.JTextField TicketPrice;
    private javax.swing.JTextField TicketPrice1;
    private javax.swing.JTextField TicketPrice2;
    private javax.swing.JSpinner Year;
    private javax.swing.JSpinner Year1;
    private javax.swing.JSpinner Year2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JComboBox<String> moviesInCgv;
    private javax.swing.JComboBox<String> moviesInGalaxy;
    private javax.swing.JComboBox<String> moviesInLotte;
    // End of variables declaration//GEN-END:variables
}
