/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.moviebooking;


import javax.swing.table.DefaultTableModel;

import com.mycompany.moviebooking.Controller.AddmovieController;
import com.mycompany.moviebooking.Controller.AuthenticationController;
import com.mycompany.moviebooking.Controller.BookingController;

/**
 *
 * @author ADMIN
 */
public class PurchaseHistoryFrame extends javax.swing.JFrame {

 
    /**
     * Creates new form PurchaseHistoryFrame
     */
    public PurchaseHistoryFrame() {
        initComponents();
        AddmovieController addmovie = new AddmovieController();
        DefaultTableModel table = (DefaultTableModel) HistoryTable.getModel();
        BookingController bookingcon = new BookingController();
        AuthenticationController au = new AuthenticationController();
        int id = au.readUserId();
        Object[] row =new Object[5];
        for(int i =0;i<bookingcon.cgvOrder.size();i++){
            if(bookingcon.cgvOrder.get(i).getUserid()==id){
                row[0]= "CGV cinema";
                row[1]= addmovie.cgv.get(bookingcon.cgvOrder.get(i).getMovieid()).getName();
                row[2]= bookingcon.cgvOrder.get(i).getChoosedseat();
                row[3]= addmovie.cgv.get(bookingcon.cgvOrder.get(i).getMovieid()).getHalls();
                row[4]= addmovie.cgv.get(bookingcon.cgvOrder.get(i).getMovieid()).getMovieTime();
                table.addRow(row);
            }
        }
        for(int i =0;i<bookingcon.galaxyOrder.size();i++){
            if(bookingcon.galaxyOrder.get(i).getUserid()==id){
                row[0]= "Galaxy cinema";
                row[1]= addmovie.galaxy.get(bookingcon.galaxyOrder.get(i).getMovieid()).getName();
                row[2]= bookingcon.galaxyOrder.get(i).getChoosedseat();
                row[3]= addmovie.galaxy.get(bookingcon.galaxyOrder.get(i).getMovieid()).getHalls();
                row[4]= addmovie.galaxy.get(bookingcon.galaxyOrder.get(i).getMovieid()).getMovieTime();
                table.addRow(row);
            }
        }
        for(int i =0;i<bookingcon.lotteOrder.size();i++){
            if(bookingcon.lotteOrder.get(i).getUserid()==id){
                row[0]= "Lotte cinema";
                row[1]= addmovie.lotte.get(bookingcon.lotteOrder.get(i).getMovieid()).getName();
                row[2]= bookingcon.lotteOrder.get(i).getChoosedseat();
                row[3]= addmovie.lotte.get(bookingcon.lotteOrder.get(i).getMovieid()).getHalls();
                row[4]= addmovie.lotte.get(bookingcon.lotteOrder.get(i).getMovieid()).getMovieTime();
                table.addRow(row);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        HistoryTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        HistoryTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cinema", "Movie Name", "Ticket Purchased", "Hall", "Movie Time"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(HistoryTable);

        jLabel1.setFont(new java.awt.Font("Sitka Subheading", 1, 14)); // NOI18N
        jLabel1.setText("Purchased History:");

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu3.setText("Booking Movie");

        jMenuItem2.setText("Booking Movie");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem2);

        jMenuBar1.add(jMenu3);

        jMenu2.setText("Log Out");
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        jMenuItem1.setText("Log Out");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        AuthenticationController au = new AuthenticationController();
        au.deleteUserId();
        new LoginFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu2ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        new BookingHomeFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PurchaseHistoryFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PurchaseHistoryFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PurchaseHistoryFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PurchaseHistoryFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PurchaseHistoryFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable HistoryTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
